#!/usr/bin/env python3
"""Wrap the engine build into src/doomPayload.js (base64 module).

The WebView bridge only moves text safely, so the emscripten bundle travels
as base64 and the page decodes it. One long line; regenerate with
scripts/build-wasm.sh rather than editing.
"""
import base64
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
blob = (root / 'wasm' / 'doom.js').read_bytes()
b64 = base64.b64encode(blob).decode('ascii')

out = root / 'src' / 'doomPayload.js'
out.write_text(
    '// Generated by scripts/build-wasm.sh. Do not edit by hand.\n'
    '// doomgeneric built with emscripten (SINGLE_FILE: wasm and the shareware\n'
    '// WAD inline), base64 so it rides through Metro and the WebView bridge\n'
    '// as plain text.\n'
    "export const DOOM_B64 = '" + b64 + "';\n"
)
print('wrote %s (%d bytes -> %d b64 chars)' % (out, len(blob), len(b64)))
